/* eslint-disable camelcase */
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="PT-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-screen flex justify-between flex-col bg-gradient-to-b from-purple-600 to-indigo-900`}
      >
        <Header />
        <div className="max-w-7xl mx-auto w-full flex-1  flex flex-col items-center justify-center bg-purple-50 mt-2">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
